oxts_gad:
  ros__parameters:
#===============================================================================
    # Output to UDP or file [0 - UDP, 1 - file]
    output_mode: 0
    # IP address of the INS to send GAD to
    unit_ip: "192.168.25.217"
    # File path to the output .gad file - BUG: crashing node with ~ in path
    file_out: "recorded.gad"

    # sensor_msgs/NavSatFix topic
    nav_sat_fix_topic: /ins/nav_sat_fix
    nav_sat_fix_pos_stream_id: 150
    # nav_msgs/Odometry topic
    odom_topic: /ins/odometry
    odom_pos_stream_id: 140
    odom_vel_stream_id: 141
    odom_att_stream_id: 142
    # geometry_msgs::msg::PoseWithCovarianceStamped
    pose_with_cov_stamped_topic: /ins/pose
    pose_with_cov_stamped_pos_stream_id: 150
    pose_with_cov_stamped_att_stream_id: 151
    # geometry_msgs::msg::TwistWithCovarianceStamped
    twist_with_cov_stamped_topic: /ins/twist
    twist_with_cov_stamped_vel_stream_id: 152


#===============================================================================