image: ros:foxy-ros1-bridge-focal
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
 - Build
 - Deploy
 - Test

before_script:
  # install package dependencies
  - apt update && apt install libboost-all-dev -y
  - apt-get install cmake
  - source /opt/ros/foxy/setup.bash

# deploy pages only on master branch
pages:
  stage: Deploy
  script:
    # Install python dependencies
    - apt install python3-pip doxygen -y
    - pip3 install sphinx sphinx_rtd_theme breathe
    # Create documentation dir and move to build dir
    - mkdir public
    - mkdir docs/build
    - cd docs/build
    - cmake ../
    - make
    - mv ../sphinx/* ../../public
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

# check that package can be compiled
compile:
  stage: Build
  script:
    - "echo Cloning OxTS GAD SDK from GitLab repo"
    - "git clone https://oxts-sdk-ci:QsKKRWRw5Bag8gzcWGns@gitlab.com/oxts/navigation/generic-aiding/gad-sdk.git" 
    - "echo Building OxTS SDK"
    - cd gad-sdk && mkdir _build && cd _build 
    - cmake .. && cmake --build . --target install
    - "echo OxTS SDK installed"
    - cd ../..
    - "echo Building ROS2 Driver"
    - mkdir -p src/oxts
    - mv oxts*/ src/oxts
    - mv test/ src/oxts/test
    - pwd
    - ls
    - ls src/oxts
    - source install/setup.bash
    - colcon build
    - ls build/tests
  artifacts:
    paths:
      - build/
      - install/
      

test:
  stage: Test
  script:
    - echo "Running unit tests"
    - ls install/tests
    - ./build/tests/tests

